name: Build and Test Terraform provider AzDo
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04]
        go-version: [1.14.10]


    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Install Dependencies
      run: make tools

    - name: Verify Vendored Dependencies
      run: make check-vendor-vs-mod


    - name: Run Format Check
      run: make fmtcheck

    - name: Run Lint Check
      run: make lint

    - name: Run Unit Test
      run: make test
#
#    - name: Run All Tests
#      run: make testacc
#
#      env:
#        AZDO_ORG_SERVICE_URL: ${{ secrets.AZDO_ORG_SERVICE_URL }}
#        AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
#        AZDO_GITHUB_SERVICE_CONNECTION_PAT: ${{ secrets.GITHUB_TOKEN }}
#        AZDO_DOCKERREGISTRY_SERVICE_CONNECTION_USERNAME: ${{ secrets.AZDO_DOCKERREGISTRY_SERVICE_CONNECTION_USERNAME }}
#        AZDO_DOCKERREGISTRY_SERVICE_CONNECTION_EMAIL: ${{ secrets.AZDO_DOCKERREGISTRY_SERVICE_CONNECTION_EMAIL }}
#        AZDO_DOCKERREGISTRY_SERVICE_CONNECTION_PASSWORD: ${{ secrets.AZDO_DOCKERREGISTRY_SERVICE_CONNECTION_PASSWORD }}
#        AZDO_TEST_AAD_USER_EMAIL: ${{ secrets.AZDO_TEST_AAD_USER_EMAIL }}
#        AZDO_BITBUCKET_SERVICE_CONNECTION_USERNAME: $(AZDO_BITBUCKET_SERVICE_CONNECTION_USERNAME)
#        AZDO_BITBUCKET_SERVICE_CONNECTION_PASSWORD: $(AZDO_BITBUCKET_SERVICE_CONNECTION_PASSWORD)
#
    - name: Run Build Script in Docker
      run: docker build -f .devcontainer/Dockerfile -t dev --build-arg GO_VERSION=${GO_VERSION} .
      env:
        GO_VERSION: ${{ matrix.go-version }}